steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast2-docker.pkg.dev/$PROJECT_ID/shampoo-api/shampoo-api:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast2-docker.pkg.dev/$PROJECT_ID/shampoo-api/shampoo-api:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'jobs', 'deploy', 'shampoo-api', '--image', 'asia-northeast2-docker.pkg.dev/$PROJECT_ID/shampoo-api/shampoo-api:latest', '--region', 'asia-northeast2', 
      
      # Secret を「ファイル」として /secrets/key.json に配置
      "--set-secrets=/secrets/key.json=gcs-key:latest",

      # Google SDK が自動でこのパスを読むように環境変数を設定
      "--set-env-vars=GOOGLE_APPLICATION_CREDENTIALS=/secrets/key.json"]

  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      ['run', 'jobs', 'execute', 'shampoo-api','--region', 'asia-northeast2']

images:
  - 'asia-northeast2-docker.pkg.dev/$PROJECT_ID/shampoo-api/shampoo-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY